# only for evaluation
DATA:
  IMG_SIZE: 96
TRAIN:
  WARMUP_EPOCHS: 5
  WARMUP_LR: 0.0001
  WEIGHT_DECAY: 0.05
  MIN_LR: 1.0e-08
  BASE_LR: 0.0005
  EPOCHS: 600
  CLIP_GRAD: 10
  LR_SCHEDULER:
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1
    NAME: cosine
  OPTIMIZER:
    BETAS:
      - 0.9
      - 0.9
    EPS: 1.0e-08
    MOMENTUM: 0.9
    NAME: adamw
  START_EPOCH: 0
MODEL:
  TYPE: WUDTnet
  NAME: gwave_wudt_noise_combinedata_all_select_patch_training
  DT:
    EMBED_DIM: 64
    DEPTHS: [3,3,6]
    NUM_HEADS: [4,8,16]
    WINDOW_SIZE: [1,1,1]