from rsf.proj import *
#import sys, os, platform
#if 'macos' in platform.platform().lower(): 
#    myprog_path='/Users/lzf/Documents/cdut_zsh_group/python/subfuctions' 
#elseif 'linux' in platform.platform().lower(): 
#    myprog_path='/home/lzf/documents/cdut_zsh_group/python/subfuctions' 
#else: 
#    myprog_path='F:linux_backuphomecdut_zsh_grouppythonsubfuctions' 
#sys.path.append(myprog_path)
#from myprog import *  
  
  
  
  
###########################################################################################
def result (data,other):
    Result (data,
             '''
             grey title=%s label1='Time' unit1='s' label2='Trace' unit2=''
             color=g screenratio=1.5 wanttitle=n pclip=99 bar=y scalebar=n
             %s 
             '''%(data,other))
def plot (data,other):
    Plot (data,
             '''
             grey title=%s label1='Time' unit1='s' label2='Trace' unit2=''
             color=g screenratio=1.5 wanttitle=n clip=3 bar=y scalebar=n
             %s 
             '''%(data,other))
def result3 (data, other):
     Result (data,
            '''
            byte pclip=99 bar=bar.rsf %s| grey3 frame1=150 frame2=50 frame3=15
            title='' label1='Time' unit1='s' label2='X' unit2='' label3='Y' unit3=''
            flat=n wantaxis=y wanttitle=n color=g point1=0.85 point2=0.64 screenratio=1.5
            '''%(other))
def plot3 (data, other):
     Plot (data,
            '''
            byte clip=3e+6 bar=bar.rsf %s| grey3 frame1=150 frame2=50 frame3=15
            title='' label1='Time' unit1='s' label2='X' unit2='' label3='Y' unit3=''
            flat=n wantaxis=y wanttitle=n color=g point1=0.85 point2=0.64 screenratio=1.5 o1num=0 d1num=2 n1tic=3 
            '''%(other))
def wig (data, other):
    Result (data,
            '''
            wiggle title=%s transp=y yreverse=y label1='Time' unit1='s' label2='Trace' unit2=''
            screenratio=1
            %s
            '''%(data, other))
def graph (data, other):
    Result (data,
            '''
            graph title=%s label1='Frequency' unit1='Hz' label2='Amplitude' unit2='' screenratio=0.5
            %s
            '''%(data, other))
###########################################################################################
Flow ('data tdata','./data/item2_mig.sgy','segyread tfile=${TARGETS[1]}')
Flow ('3ddata','data tdata','intbin4 tfile=${SOURCES[1]} xkey=5 ykey=73 ')
Flow('./data/data.dat','3ddata','rsf2bin')
result3('3ddata','')


End ()
